- name: Update apt-packages on linux vms
  hosts: all
  any_errors_fatal: true
  gather_facts: false

  tasks:
    - name: Install time sync packages
      shell: |
        sudo apt-mark auto chrony && sudo apt install -y systemd-timesyncd
        sudo apt install -y ntpsec-ntpdate

    - name: Sync time with NTP server
      shell: |
        sudo ntpdate -u {{ lookup('ansible.builtin.env', 'NFS_SERVER') }}
    
    - name: Enable and start time sync service
      shell: |
        sudo systemctl enable systemd-timesyncd
        sudo systemctl start systemd-timesyncd
        sudo systemctl status systemd-timesyncd
      