# =========================
# OBSERVABILITY ADDON - METRICS SERVER
# =========================
- hosts: control_plane
  any_errors_fatal: true

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  tasks:
    - name: Register harbor docker secret in default namespace
      environment: 
        HARBOR_REGISTRY_URL: "{{ lookup('ansible.builtin.env', 'HARBOR_REGISTRY_URL') }}"
        HARBOR_USERNAME: "{{ lookup('ansible.builtin.env', 'HARBOR_USERNAME') }}"
        HARBOR_PASSWORD: "{{ lookup('ansible.builtin.env', 'HARBOR_PASSWORD') }}"
      shell: |
        SECRET=$(kubectl get secrets | grep harbor-registry-secret)
        
        if [ -z "$SECRET" ]; then
          kubectl create secret docker-registry harbor-registry-secret \
            --docker-server="$HARBOR_REGISTRY_URL" \
            --docker-username="$HARBOR_USERNAME" \
            --docker-password="$HARBOR_PASSWORD" \
            --namespace=default
        fi
