# =========================
# STORAGECLASS ADDON - NFS
# =========================
- hosts: control_plane
  any_errors_fatal: true

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  tasks:
    - name: Install helm cli
      become_user: root
      shell: snap install helm --classic

    - name: Create NFS storage class
      shell: |
        helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

        helm upgrade --install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
        --create-namespace \
        --namespace nfs-provisioner \
        --set nfs.server={{ lookup('ansible.builtin.env', 'NFS_SERVER') }} \
        --set nfs.path={{ lookup('ansible.builtin.env', 'NFS_MOUNT') }} \
        --set storageClass.name=nfs-storage \
        --set storageClass.defaultClass=true

    - name: Wait for NFS storage class to be ready
      ansible.builtin.command: >
        kubectl -n nfs-provisioner rollout status deploy/nfs-subdir-external-provisioner --timeout=300s
      changed_when: false