all:
  hosts:
    k8s-node-1:
      ansible_host: k8s-node-1
      ansible_user: $VM_USER
      ansible_ssh_pass: $VM_PASSWORD
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_password: $VM_SUDO_PASSWORD
    k8s-node-2:
      ansible_host: k8s-node-2
      ansible_user: $VM_USER
      ansible_ssh_pass: $VM_PASSWORD
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_password: $VM_SUDO_PASSWORD
    k8s-node-3:
      ansible_host: k8s-node-3
      ansible_user: $VM_USER
      ansible_ssh_pass: $VM_PASSWORD
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_password: $VM_SUDO_PASSWORD
control_plane:
  hosts:
    k8s-node-1:
      ansible_host: k8s-node-1
      ansible_user: $VM_USER
      ansible_ssh_pass: $VM_PASSWORD
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_password: $VM_SUDO_PASSWORD
worker_str:
  hosts:
    k8s-node-2:
      ansible_host: k8s-node-2
      ansible_user: $VM_USER
      ansible_ssh_pass: $VM_PASSWORD
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_password: $VM_SUDO_PASSWORD
    k8s-node-3:
      ansible_host: k8s-node-3
      ansible_user: $VM_USER
      ansible_ssh_pass: $VM_PASSWORD
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_password: $VM_SUDO_PASSWORD
