# =========================
# INGRESS CONTROLLER ADDON - TRAEFIK
# =========================
- hosts: control_plane
  any_errors_fatal: true

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  tasks:
    - name: Copy traefik values file
      copy:
        src: ../../templates/traefik-values.yaml
        dest: /tmp/traefik-values.yaml
        mode: "0644"

    - name: Install / Upgrade traefik ingress controller
      shell: |
        helm repo add traefik https://traefik.github.io/charts
        helm upgrade --install traefik traefik/traefik \
          --create-namespace --namespace traefik \
          -f /tmp/traefik-values.yaml

    - name: Wait for traefik to be ready
      ansible.builtin.command: >
        kubectl -n traefik rollout status deploy/traefik --timeout=300s
      changed_when: false