apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
   storageclass.kubernetes.io/is-default-class: "true"
  name: local-storage
provisioner: kubernetes.io/no-provisioner # indicates that this StorageClass does not support automatic provisioning
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete