---
# =========================
# UPGRADE ADDONS ON CONTROL PLANE
# =========================
- import_playbook: ../playbooks/modules/kubernetes/cni.yaml
- import_playbook: ../playbooks/modules/addons/loadbalancer-addon.yaml
- import_playbook: ../playbooks/modules/addons/storage-class-addon.yaml
- import_playbook: ../playbooks/modules/addons/ingress-controller-addon.yaml
- import_playbook: ../playbooks/modules/addons/dashboard-addon.yaml
- import_playbook: ../playbooks/modules/addons/observability-addon.yaml

- import_playbook: ../playbooks/modules/addons/argocd-addon.yaml
  when: argocd_addon == true | default(false)